panels/background/gnome-background-panel.desktop.in.in, panels/bluetooth/gnome-bluetooth-panel.desktop.in.in, panels/color/gnome-color-panel.desktop.in.in, panels/datetime/gnome-datetime-panel.desktop.in.in, panels/display/gnome-display-panel.desktop.in.in, panels/info/gnome-info-panel.desktop.in.in, panels/keyboard/gnome-keyboard-panel.desktop.in.in, panels/mouse/gnome-mouse-panel.desktop.in.in, panels/network/gnome-network-panel.desktop.in.in, panels/notifications/gnome-notifications-panel.desktop.in.in, panels/online-accounts/gnome-online-accounts-panel.desktop.in.in, panels/power/gnome-power-panel.desktop.in.in, panels/printers/gnome-printers-panel.desktop.in.in, panels/privacy/gnome-privacy-panel.desktop.in.in, panels/region/gnome-region-panel.desktop.in.in, panels/search/gnome-search-panel.desktop.in.in, panels/sharing/gnome-sharing-panel.desktop.in.in, panels/sound/data/gnome-sound-panel.desktop.in.in, panels/universal-access/gnome-universal-access-panel.desktop.in.in, panels/user-accounts/data/gnome-user-accounts-panel.desktop.in.in, panels/wacom/gnome-wacom-panel.desktop.in.in
These aren't apps -- they're simply launchers for gnome-control-center.
They should not be shown as apps in the UI at all.
https://bugzilla.gnome.org/show_bug.cgi?id=712246
endlessm/eos-shell#4371
=> Add NoDisplay to all gnome-control-center panel .desktop files

debian/control
Our new system-config-printer replaces the system-config-printer package
with a virtual provides from system-config-printer-gnome. Apt seems to
get confused about the existence of a real system-config-printer in our
repo from extra, which pulls in unwanted dependencies. Prefer
system-config-printer-gnome here to avoid that situation.
[endlessm/eos-shell#4481]
=> Recommend system-config-printer-gnome

panels/power/cc-power-panel.c
We don't have any user-reachable way to suspend nor hibernate so those
two options have been removed from the power configuration panel.
[endlessm/eos-shell#4625]
=> Shell: Removed out the "Suspend and Power Off" block in power panel

panels/region/cc-region-panel.c
Not doing this will lead to (probably undesired) inconsistencies when
changing the language, since many locale-dependant strings will still be
rendered considering the previous language format (e.g. days of the week).
[endlessm/eos-shell#3586]
=> Update the locale format along with the language when it changes

panels/display/cc-display-panel.c
Actually we do not show the overscan option for LVDS screens.
[endlessm/eos-shell#4799]
=> display: Do not show overscan for internal laptop display

panels/datetime/cc-datetime-panel.c, po/es.po
Always use a locale-specific translation for the AM/PM strings if it's
available, but do not prevent users from using 12-h formats if it's not,
and use a fallback "AM / PM" strings for those situations.
[endlessm/eos-shell#4772]
=> datetime: Always allow to select a 12-h format, regardless of locale

panels/sharing/cc-remote-login-helper.c, panels/sharing/cc-remote-login.c
Debian calls it "ssh.service".
[endlessm/eos-shell#4824]
=> sharing: use correct name for SSH service

panels/power/cc-power-panel.c
Show "Suspend & Power Off" section only when system can suspend
Instead of disabling this section entirely, ask logind's D-Bus service
'org.freedesktop.login1.Manager.CanSuspend' to determine whether it
should be visible or not, similar to what GDM and the Shell already do.
Also, fix two critical messages while at it.
[endlessm/eos-shell#4655]
=> Use org.freedesktop.login1.Manager.CanSuspend from the power panel

panels/info/Makefile.am, panels/info/cc-info-panel.c, panels/info/eos-updater.xml
It was determined that the ostree daemon was not upstreamable, so the
interface has moved over to an Endless specific com.endlessm.Updater.
Copy in eos-updater.xml and adjust accordingly. The interface usage was
changed slightly so that the object is EosUpdater.
[endlessm/eos-shell#5087]
=> info: Adjust to new dbus interface

panels/background/bg-colors-source.c, panels/background/bg-source.c, panels/background/bg-wallpapers-source.c, panels/background/cc-background-chooser-dialog.c, panels/background/cc-background-item.c, panels/background/cc-background-item.h, panels/background/cc-background-panel.c
Setting pixbufs as GIcons causes the CellRendererPixbuf to try to load
it at 32px ever since a GTK+ upgrade, so we can't do this anymore.
Upstream fixed this by porting away from GtkCellRenderer and instead to
GtkFlowBox, so that's why this hasn't been fixed there.
Setting the backgrounds as pixbufs means we can't have the GtkIconTheme
code apply emblems for time-changing backgrounds, but we don't ship any
time-changing backgrounds, so it shouldn't cause any major difference.
[endlessm/eos-shell#5356]
=> background: Set background items as pixbufs, not GIcons

panels/region/cc-region-panel.c
Whenever the user changes the language for the session we also change
the language used for format strings, to be consistent with the previous
selection unless the user explicitly changes that later on.
However, there's no need to set the org.gnome.system.locale.region GSetting
property in that case, since being undefined will already mean that
overriding the default language is not needed.
[endlessm/eos-shell#5617]
=> region: Override language for format strings when different from default

panels/info/cc-info-panel.c, panels/info/info.ui, shell/cc-window.c
When the screen size is big enought, make the icon views from
the overview page set the number of columns to 6, imitating the
behavior we had before. When the screen size is small, unset the
number of columns, making it adapt to small screen sizes.
[endlessm/eos-shell#6133]
=> window: set overview columns when screen size is big

panels/sound/gvc-mixer-dialog.c
When looking up a bar for a particular stream, special-case the input
and output bars/streams, as they will not be added to the "bars"
hashtable (which is, as per comment, only for applications and the sound
events bar).
https://bugzilla.gnome.org/show_bug.cgi?id=738869
[endlessm/eos-shell#5695]
=> sound: Fix output/output bars not following external changes

shell/cc-panel.c
After the introduction of Gtk+ 3.20, many applications
had their UI broken because Gtk+ is more strict regarding
allocation now. The control center also suffers from this
side effect in various panels.
To fix that, make the broken panels expand vertically.
https://phabricator.endlessm.com/T11747
=> panels: always expand vertically

panels/display/cc-display-panel.c
Upstream added a new row to the GtkGrid, so we need to adjust our
offsets here accordingly.
This commit should be squashed into "display: Add option to enable and
disable overscan compensation" during the next rebase.
https://phabricator.endlessm.com/T12165
=> Fixup for "Add option to enable and disable overscan compensation"

panels/info/cc-info-panel.c
If the error is set here, it is an error to pass it to the code
initializing the session proxy.
https://phabricator.endlessm.com/T12564
=> info: clear error before re-using it

panels/power/cc-power-panel.c
We check with NetworkManager whether a wireless device exists to decide
whether or not to display these toggles. NetworkManager says no, we hide
the toggles, then we call gtk_widget_show_all() and undo our work. Sad!
Actually pressing the toggles triggers the check again, and causes both
listbox rows to shockingly disappear.
This fix is not needed on the master branch because, since the port to
libnm 1.2, the check is now scheduled on the main loop, to run after
this function completes, inadvertantly fixing this bug.
https://bugzilla.gnome.org/show_bug.cgi?id=771148
(Note that commit message refers to the upstream master branch where this is fixed, but it's still needed on Endless master which is based off the upstream gnome-3-20 branch.)
https://phabricator.endlessm.com/T13205
=> power: Fix hiding wi-fi, mobile broadband toggles

panels/power/cc-power-panel.c
This toggle is always set to off when the panel is opened. We should
check whether it's on or not when opening the panel. Currently we are
only subscribed to changes, so we don't check the wifi state until it's
toggled on or off after the panel has been opened the first time.
https://bugzilla.gnome.org/show_bug.cgi?id=771564
https://phabricator.endlessm.com/T13205
=> power: Fix wifi device state when opening power panel

panels/info/cc-info-panel.c, panels/info/eos-updater.xml
This depends on an eos-updater API addition:
https://github.com/endlessm/eos-updater/pull/44
https://phabricator.endlessm.com/T13951
=> info: hide update label on live boots

panels/display/cc-display-panel.c
When the overscan feature is not supported by the output, we
still show an useless checkbox that does nothing and has a high
potential to confuse users.
Fix that by only showing the checkbox when the overscan feature
is supported.
https://phabricator.endlessm.com/T13812
=> display-panel: don't show overscan toggle when unsupported

panels/info/Makefile.am, panels/info/cc-info-panel.c
If a configuration file in /etc/eos-branding/gnome-control-center/info.conf
is found, it defines the path to a branding-specific logo and such a file
exists in disk, then gnome-control-center will use that one to override
Endless's logo in the "info" panel.
https://phabricator.endlessm.com/T15836
=> Allow defining branding-specific logos for the "info" panel.

panels/privacy/cc-privacy-panel.c
As xdg-app has been renamed to Flatpak, the permission store's bus name
and interface name have been changes as well.
https://bugzilla.gnome.org/show_bug.cgi?id=766603
=> privacy: Update for PermissionStore DBus API changes

panels/user-accounts/data/password-dialog.ui
The labels for the the options of setting a password on their next log
in were mistakenly inconsistent.
https://phabricator.endlessm.com/T17270
=> user-accounts: Fix using the same label for set-password-on-login option

panels/common/cc-common-language.c
The FBE has been patched to show the 8 best-supported languages in
Endless OS, sorted by frequency. Update here so that new users /
language settings have the same selection.
https://phabricator.endlessm.com/T18020
=> update language chooser to match FBE

panels/search/cc-search-panel.c
Due to a bug in the flatpak builds, we have been accidentally
appending the search-provider.ini files with "DefaultDisabled=true".
This causes the default behavior for Endless apps to have
search disabled unless explicitly enabled in a gsetting.
Since global search of Endless apps is an important feature
of our OS, we include a hack here to pretend that Endless apps
(app ID starting with "com.endlessm.") do not set this flag.
While the proper fix is to fix the flatpak builder,
rebundle all Endless flatpaks, and update all Endless flatpaks
installed on user machines, that is a huge endeavor and not
something we can quickly patch, so we should live with this
hack for a while until we have fixed our latest flatpaks
and given users plenty of time to have updated all their apps.
We did not …
=> cc-search-panel: ignore DefaultDisabled for Endless apps

debian/rules
We intentionally moved the location of these files
from /var/eos-image-defaults to /var/lib/eos-image-defaults
but failed to update gnome-control-center accordingly.
https://phabricator.endlessm.com/T18935
=> debian/rules: check for conf files in /var/lib/eos-image-defaults

panels/display/cc-display-panel.c
This change is no longer a good idea now we also have the
"Night Light" option showing up in this panel.
This reverts commit 5ca23d62567ef3eba506466c9735029e5e0fe6eb.
https://phabricator.endlessm.com/T19358
=> Revert "display: pre-select output if there's only one"

debian/rules
dh_auto_configure defaults to running configure, which means we can’t
easily build the package from git.
https://phabricator.endlessm.com/T19532
=> debian: Use autogen.sh instead of dh_auto_configure

panels/sound/data/icons/scalable/devices/Makefile.am, panels/sound/data/icons/scalable/devices/audio-speaker-center-back-testing.svg, panels/sound/data/icons/scalable/devices/audio-speaker-center-back.svg, panels/sound/data/icons/scalable/devices/audio-speaker-center.svg, panels/sound/data/icons/scalable/devices/audio-speaker-left-back-testing.svg, panels/sound/data/icons/scalable/devices/audio-speaker-left-back.svg, panels/sound/data/icons/scalable/devices/audio-speaker-left-side-testing.svg, panels/sound/data/icons/scalable/devices/audio-speaker-left-side.svg, panels/sound/data/icons/scalable/devices/audio-speaker-left-testing.svg, panels/sound/data/icons/scalable/devices/audio-speaker-left.svg, panels/sound/data/icons/scalable/devices/audio-speaker-mono-testing.svg, panels/sound/data/icons/scalable/devices/audio-speaker-mono.svg, panels/sound/data/icons/scalable/devices/audio-speaker-right-back-testing.svg, panels/sound/data/icons/scalable/devices/audio-speaker-right-back.svg, panels/sound/data/icons/scalable/devices/audio-speaker-right-side-testing.svg, panels/sound/data/icons/scalable/devices/audio-speaker-right-side.svg, panels/sound/data/icons/scalable/devices/audio-speaker-right-testing.svg, panels/sound/data/icons/scalable/devices/audio-speaker-right.svg, panels/sound/data/icons/scalable/devices/audio-speaker-testing.svg, panels/sound/data/icons/scalable/devices/audio-subwoofer-testing.svg, panels/sound/data/icons/scalable/devices/audio-subwoofer.svg
Apply patch for bgo 775170 that adds the missing icon for mono speakers, and re-style all speaker icons.
https://phabricator.endlessm.com/T19634
=> Fix missing icon for mono speaker

debian/rules
This reverts commit 50fd5284b998e6642828af28dfbf7c4b4bed0942.
The upstream tarball does not contain an autogen.sh script, so the
package build fails when building from a tarball rather than from git.
Since we build from tarballs, this is embarrassing.
https://phabricator.endlessm.com/T19532
=> Revert "debian: Use autogen.sh instead of dh_auto_configure"

configure.ac, panels/info/cc-info-panel.c
The current code relies on GLib API and uses the
available mounts to calculate the available partition
size. This is because this code assumes that more
than one OS can be installed in the same drive, and
wouldn't make sense to show the whole disk size in
this situation.
However, Endless OS is not meant to be installed with
other OSes on different partitions, and for our partners
it might be bad to show a disk space smaller than what
they put on their hardware.
Fix that by using the UDisks API to get the real size
of the full disks.
https://phabricator.endlessm.com/T19907
=> info: use UDisks to retrieve disk size

panels/info/cc-info-panel.c
Checking if a given drive is removable is not enough, because eMMC
drives are legitimately removable, and also because the DBus 'Removable'
property is essentially a guess and should not be used alone.
This commit, then, only considers drives that are ejectable, removable
and media-removable simultaneously when deciding which drives to skip.
https://phabricator.endlessm.com/T20504
=> info: Check if drive is both removable and media-removable

panels/network/connection-editor/ce-page-details.c, panels/network/connection-editor/details-page.ui
NetworkManager supports marking a connection as metered, meaning
that connection is e.g. charged by its usage or extremely limited.
When a network is metered, background network usage must cease
and the behavior of the various OS pieces must be adjusted.
This patch adds a switch to set a connection as metered or not.
The property is imediately propagated to NetworkManager.
https://phabricator.endlessm.com/T20771
=> connection-editor: Expose metered connection switch

panels/network/connection-editor/ce-page-details.c, panels/network/connection-editor/details-page.ui
Per guidance of the design team, since the dialog has not
enough room for switches.
https://phabricator.endlessm.com/T20771
=> network: Turn metered data switch into a check button

panels/power/power.ui
Pad out the 15-30 minutes mark with 5 minute increments. This also means
that the new 20-minute default for suspending is now in the list, and
will be selected when the panel is opened, rather than the 30 minutes
option.
See https://bugzilla.gnome.org/show_bug.cgi?id=681869
https://phabricator.endlessm.com/T20634
=> power: Add 20 and 25 minutes suspend timeouts

panels/sharing/sharing.ui
This is a sentence, so it should use sentence case, where only proper nouns like “Android” are capitalized mid-sentence.
I accept that other descriptions throughout the control center are not consistent on this point. Some, but not all, follow the convention where the name of the feature is in Title Case. Regardless, “Devices” and “Network” should certainly not be capitalized.
https://phabricator.endlessm.com/T20381
https://phabricator.endlessm.com/T20668
=> sharing: fix case in content sharing description

panels/display/cc-display-panel.c
The GVariant constructed here would be useless otherwise, since there are
no outputs to show the labels for. Besides, calling g_variant_builder_close
in this scenario would hit an assertion and the program would crash.
https://gitlab.gnome.org/GNOME/gnome-control-center/issues/12
https://phabricator.endlessm.com/T20655
=> display: Early return in monitor_labeler_show() if no outputs are available

panels/background/gnome-background-panel.desktop.in.in, panels/bluetooth/gnome-bluetooth-panel.desktop.in.in, panels/color/gnome-color-panel.desktop.in.in, panels/datetime/gnome-datetime-panel.desktop.in.in, panels/display/gnome-display-panel.desktop.in.in, panels/info/gnome-default-apps-panel.desktop.in.in, panels/info/gnome-info-overview-panel.desktop.in.in, panels/info/gnome-info-panel.desktop.in.in, panels/info/gnome-removable-media-panel.desktop.in.in, panels/keyboard/gnome-keyboard-panel.desktop.in.in, panels/mouse/gnome-mouse-panel.desktop.in.in, panels/network/gnome-network-panel.desktop.in.in, panels/network/gnome-wifi-panel.desktop.in.in, panels/notifications/gnome-notifications-panel.desktop.in.in, panels/online-accounts/gnome-online-accounts-panel.desktop.in.in, panels/power/gnome-power-panel.desktop.in.in, panels/printers/gnome-printers-panel.desktop.in.in, panels/privacy/gnome-privacy-panel.desktop.in.in, panels/region/gnome-region-panel.desktop.in.in, panels/search/gnome-search-panel.desktop.in.in, panels/sharing/gnome-sharing-panel.desktop.in.in, panels/sound/data/gnome-sound-panel.desktop.in.in, panels/universal-access/gnome-universal-access-panel.desktop.in.in, panels/updates/gnome-updates-panel.desktop.in.in, panels/user-accounts/data/gnome-user-accounts-panel.desktop.in.in, panels/wacom/gnome-wacom-panel.desktop.in.in
As per the Startup Notification Spec, when an application declares this
in its desktop file, it the launcher (e.g. the shell) will initiate the
startup process, expecting the launchee to finish it with a "remove" X
message once it's ready, unless there's a failure launching it.
The problem here is that this panel-specific desktop files declaring that
key confuses the shell, since it will make it initiate the startup process
but then no "remove" message is ever received if g-c-c was already running,
since the newly launched process will realize it's not the main instance and
will exit gracefully after handing over control of the situation to the
original process, with exit code 0, leaving the startup process unfinished.
Due to this, the shell will keep waiting for a supposedly new …
=> Don't declare StartupNotify=true in panel-specific desktop files

panels/updates/cc-tariff-editor.c
There were 2 problems found on the clock format code:
1. It was mistakenly putting the start hour in the end hour spinner.
2. It was using UTC datetimes when it should've been using the local timezone.
https://phabricator.endlessm.com/T22384
=> Fix bugs on clock format handling code

.gitmodules, panels/network/cc-wifi-panel.c
Our help pages are forked from GNOME 3.10, and don't have a net-wireless
page.
https://phabricator.endlessm.com/T23340
=> wifi: show generic "network" help page

debian/rules
This lives in /var/lib/eos-image-defaults, not /var/eos-image-defaults.
The wrong value was introduced with the rebase for 3.3, in June 2017,
and went unnoticed until now.
See https://github.com/endlessm/gnome-control-center/commit/987506c90192e69e43ff4e5b850e90abf8948cc1#diff-d2b2229a977ef7e99780f2207c29b503
https://phabricator.endlessm.com/T24422
=> rules: fix wrong vendor configuration file path

panels/power/cc-power-panel.c
The pending-charge state means AC power is on but the battery is not
being charged. This can happen because its charge is above a certain
threshold, to avoid short charging cycles and prolong the battery's
life, or because the PSU is not powerful enough to charge the batteries.
Instead of lying to the user about something being estimated, we should
simply tell the truth and set the label to "Not Charging".
https://phabricator.endlessm.com/T24044
=> power: Label the PENDING_CHARGING state as "Not Charging" 

panels/color/gnome-color-panel.desktop.in.in, panels/datetime/gnome-datetime-panel.desktop.in.in, panels/power/gnome-power-panel.desktop.in.in, panels/printers/gnome-printers-panel.desktop.in.in, panels/universal-access/gnome-universal-access-panel.desktop.in.in
gnome-settings-daemon emits notifications related to these five control
panels. If we add X-GNOME-UsesNotifications to their desktop files, the
user will be able to control the notifications.
(Backport to EOS: Support additional notification in
panels/universal-access.)
https://wiki.gnome.org/Initiatives/GnomeGoals/NotificationSource
https://phabricator.endlessm.com/T20990
=> panels: Add X-GNOME-UsesNotifications to several desktop files

panels/user-accounts/gs-content-rating.c, panels/user-accounts/org.gnome.controlcenter.user-accounts.policy.in, panels/user-accounts/um-app-permissions.c, panels/user-accounts/um-app-permissions.h, panels/user-accounts/um-user-panel.c
Essentially a cherry-pick of the relevant bits of https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/157. Note that it hasn’t been reviewed or merged upstream yet, so we might diverge if they request changes.
This is based on #149. Only the top commit is relevant.
=> T23897 Fix locale parsing for gs_utils_content_rating_system_from_locale()

panels/user-accounts/gs-content-rating.c, panels/user-accounts/org.gnome.controlcenter.user-accounts.policy.in, panels/user-accounts/um-app-permissions.c, panels/user-accounts/um-app-permissions.h, panels/user-accounts/um-user-panel.c
This is an alternative to https://github.com/endlessm/gnome-control-center/pull/151 (mutually exclusive).
This approach adds some additional CSM ↔ OARS mappings so that mappings exist for CSM ages 16 and 17, which are mapped to from several locale-specific ratings systems.
It fixes all mappings (unlike #151, which leaves one OFLCNZ R16 and CERO D broken), but at the cost of diverging from upstream appstream-glib’s set of CSM ↔ OARS mappings.
This is based on https://github.com/endlessm/gnome-control-center/pull/150, so only the top two commits are relevant.
=> T23897 Different approach to fixing age mapping with parental controls

panels/user-accounts/um-app-permissions.c
Currently, we can’t really support blacklisting non-flatpak apps, as
they could be exec()ed from anywhere; flatpak apps typically need to be
run via `flatpak run`, which is easier to add blacklisting support to.
(It is possible to run a flatpak app with a manual bwrap invocation, but
that’s a lot harder.)
https://phabricator.endlessm.com/T24022
=> user-accounts: Don’t list non-flatpak apps in parental controls

panels/user-accounts/data/user-accounts-dialog.ui
Otherwise it isn’t included in the tab focus cycle, and can’t be
navigated to with the tab key.
https://phabricator.endlessm.com/T24990
=> user-accounts: Allow ‘Remove User’ button to be focused

panels/updates/gnome-updates-panel.desktop.in.in
So that it appears when searching for ‘background data’ or ‘background
updates’ or ‘metered data’.
---
*Note*: This is a translatable string change. There’s no Phabricator issue for it, and no schedule driving its acceptance. It’s just a drive-by fix for something I noticed while working on https://phabricator.endlessm.com/T24117.
=> updates: Add additional keywords to ‘Automatic Updates’ panel

panels/network/connection-editor/details-page.ui
The other checkboxes on this page all have mnemonics. It seems unfair
for the background data usage one to be left out of the party.
---
*Note*: This is a translatable string change. There’s no Phabricator issue for it, and no schedule driving its acceptance. It’s just a drive-by fix for something I noticed while working on https://phabricator.endlessm.com/T24117.
=> network: Add mnemonic for ‘Restrict background data usage’ checkbox

panels/user-accounts/um-app-permissions.c
When disabling parental controls, the string ‘Disabled’ doesn’t fit well
in the UI, since the UI ends up reading “Show Apps Suitable For:
Disabled”, which sounds like it’s for disabled users, rather than that
the feature is disabled.
Use ‘No Restriction’ instead.
The string ‘Disabled’ was originally used to allow re-use of existing
translations.
=> user-accounts: Use ‘No Restriction’ rather than ‘Disabled’ for ages

debian/gnome-control-center-data.install
We are no longer installing a custom xdg-user-dirs desktop file.
https://phabricator.endlessm.com/T25445
=> debian: Drop xdg-user-dirs directory

panels/background/Makefile.am, panels/background/bg-pictures-source.c, panels/background/gnome-wallpapers.desktop.in, po/POTFILES.in
This is a partial revert of commit
84eca50c748fe982392bf9bad8084107061f8918. It drops
gnome-wallpapers.desktop as a way of specifying where g-c-c should look
for wallpapers, and instead hard-codes the directory to look in as a
subdirectory of XDG_PICTURES_DIR.
There are several reasons for this:
• It was using a custom GLib API
(g_get_user_special_dir_for_desktop_id()) which was not upstream and
wasn’t going to be accepted upstreamed.
• Looking at `man 5 user-dirs.dirs`, it says “the format of
user-dirs.dirs is designed to allow direct sourcing of this file in
shell scripts”, but if gnome-wallpapers.desktop were ever overridden
in user-dirs.dirs, that would break, as `gnome-wallpapers.desktop` is
not a valid sh variable name. So the default value could only ever be
used.
• Nautilus’ ‘Set …
=> background: Stop using a custom XDG dir for wallpapers

panels/user-accounts/um-app-permissions.c
The default for valign is GTK_ALIGN_FILL; this caused the switches to be stretched vertically, which may have looked fine for Old Adwaita but looks bad for New Adwaita. Since we are sticking with g-c-c 3.26 for eos 3.6.0, we need to fix this independently of the rebase.
Before: ![Screenshot from 2019-04-26 16-04-22](https://user-images.githubusercontent.com/86760/56818726-289bb700-6840-11e9-8979-3dc265f76b3b.png)
After: ![Screenshot from 2019-04-26 16-18-58](https://user-images.githubusercontent.com/86760/56818724-289bb700-6840-11e9-9eb5-7f1e34725c5b.png)
https://phabricator.endlessm.com/T25193
=> user-accounts: vertically centre per-app switches

panels/background/cc-background-item.c
Fixes a copy-paste error introduced in https://github.com/endlessm/gnome-control-center/pull/169
https://phabricator.endlessm.com/T26592
=> fixup! background: Remove GdkColor deprecation warnings

panels/search/cc-search-panel.c
This fixes a crash when clicking on Search on latest master.
https://phabricator.endlessm.com/T25338
=> Fix double free when discovering search providers

panels/search/cc-search-panel.c, panels/search/meson.build, panels/user-accounts/cc-app-permissions.c, panels/user-accounts/gs-content-rating.c, panels/user-accounts/gs-content-rating.h, panels/user-accounts/meson.build
eos-parental-controls is renamed to malcontent for upstreaming
purposes hence, we should move to libmalcontent so that it can
be dropped from Endless package-management system as well.
This commit does not introduce any functional changes. In the next
rebase cycle, this commit can be squashed with the commit where the
parental controls is introduced (c315ab1ed).
https://phabricator.endlessm.com/T26995
=> parental-controls: Migrate to malcontent

panels/applications/cc-applications-panel.c, panels/applications/cc-applications-panel.ui
A web app can be added to desktop for easy access via:
Right-click the desktop → Add Website...
These web app have app-id prefixed with "eos-link-".
gnome-control-center 3.32 introduced a new "Applications"
panels for applications' managing details (managing permissions,
disk space usage etc.). The enormous list of "eos-link-"
webapps ended up in this applications panel where basically
have very minimal information to show/manage. Also, many of
them are non-English speaking apps, which inhibits the purpose
of search in this particular panel.
https://phabricator.endlessm.com/T27007
=> applications: Filter out "eos-link-" Endless-specific webapps

panels/applications/cc-applications-panel.c
In Endless, gnome-software is patched to not display itself. (The
rationale is that it looks odd for the App Center to be listed as an app
inside itself; everywhere else we treat it as a system component, not as
something with its own “personality”.)
As a result, selecting App Center in this panel then clicking “Show in
App Center” launches the App Center with a “No Application Found” error.
Hide this button when displaying the App Center page in the applications
panel.
https://phabricator.endlessm.com/T27065
=> applications: hide “Show in App Center” for App Center

panels/user-accounts/cc-app-permissions.c, panels/user-accounts/cc-app-permissions.ui, panels/user-accounts/meson.build
Note that in this implementation individual browsers are not listed in the restrict apps list and can only be disabled via the `Web Browsers` switch. This was done on purpose as supporting both options to disable browsers would require more discussions on the UI/usability side of things. See https://phabricator.endlessm.com/T26895#730545 for more details.
https://phabricator.endlessm.com/T27064
=> parental controls: Add setting to disable all browsers

panels/user-accounts/cc-app-permissions.c, panels/user-accounts/cc-app-permissions.ui
Particularly, hide "App Installation" and "Install Apps for all Users".
The reason is that, we will always allow administrators to install
apps without the polkit challenge, as this was the default behaviour
historically.
During next rebase, this commit can be squashed with:
c825ff3fd parental-controls: Enable parental-controls for Administrators
https://phabricator.endlessm.com/T26968
=> parental controls: Hide defunct switches for administrators

panels/applications/cc-applications-panel.c
These are not "real" applications, so we should hide them from the
Applications panel (just as we do for web apps).
https://phabricator.endlessm.com/T27105
=> applications: hide "Get ____" launchers

panels/search/cc-search-locations-dialog.c, panels/sound/cc-volume-slider.c
These are the only two non-translation commits on the gnome-3-34 branch since the merge base between our master and gnome-3-34, namely e369c8c19772368c68faa13b9d31999fc0a5fe87.
I have not merged the gnome-3-34 branch for lack of https://gitlab.gnome.org/wjt/translate-o-tron-3000/issues/1.
https://phabricator.endlessm.com/T27886
=> Cherry-pick upstream fix for crash on clicking 'Search Locations'

panels/display/cc-display-panel.ui
On EndlessOS, the primary display contains the task bar, not the top bar
nor the Activities.
https://phabricator.endlessm.com/T27898
=> display: Adapt primary display description for EndlessOS

panels/user-accounts/cc-avatar-chooser.c, shell/org.gnome.ControlCenter.gschema.xml
This patch provides an easy way to override default faces using a
settings configuration that can be used in gnome-initial-setup too so
downstream can override default avatar faces without the need of a
patch.
https://phabricator.endlessm.com/T27788
=> user-accounts: Use custom setting to override faces

panels/common/cc-language-chooser.ui
Increase height so that "view-more-symbolic" icon appears
by default when the language-dialog is displayed. This
improves UI-feedback for the user for browsing additional
language entries.
Upstream MR:
https://gitlab.gnome.org/GNOME/gnome-control-center/merge_requests/633
If the above MR is merged, this commit can be dropped in
the next rebase.
---------
- No associated task.
- Was not a clean cherry-pick from MR due to these [changes ](https://gitlab.gnome.org/GNOME/gnome-control-center/commit/23a7401)I suppose.
- This unblocks my work on fixing openQA test : `parental_controls_setup`
https://github.com/endlessm/eos-openqa-tests/commits/uajain/staging-parental-controls-setup
=> cc-language-dialog: Increase height to 475px

panels/user-accounts/cc-app-permissions.c
When a user who is not a sudoer clicks on another user in the Users
panel, if the panel is not unlocked it leads to an error message like
this:
Error retrieving app filter for user 'andrunko': Not allowed to query app filter data for user 1000
However it's expected behavior that the mct_manager_get_app_filter()
call will fail in this case, so check for such an error message and
clear it.
https://phabricator.endlessm.com/T28600
=> T28600 unresponsive polkit dialog (quiet error)

panels/display/cc-display-config-dbus.c
Gnome-control-center checks the enumerated display modes by
cc_display_config_is_scaled_mode_valid()
...
cc_display_config_dbus_is_scaled_mode_valid()
to exclude unusable low resolutions.
However, it is the current using resolution that going to be tested by
is_scaled_mode_allowed() in is_scale_allowed_by_active_monitors(), if it
is global scaled required or configured as cloning mode originally.
Therefor, it will check current using resolution again and again,
instead of the enumerated one. This leads gnome-control-center building
wrong resolution list on the panel.
This patch replaces the current mode with the enumerated mode to have
the correct resolution to be tested by is_scaled_mode_allowed().
https://phabricator.endlessm.com/T29501
=> display: Fix the resolution going to be tested

panels/metrics/gnome-metrics-panel.desktop.in.in
xgettext has been fixed to not extract Icon= fields for translation. I
took care of backporting the patch to Endless OS.
All other panels' desktop files have NoDisplay=true, except this one. As
a result it shows up twice in search results: once as an app, and once
in the Settings search provider.
https://phabricator.endlessm.com/T28873
=> fixup! privacy: Add metrics panel controlling metrics service integration

meson.build, panels/user-accounts/cc-user-panel.c, panels/user-accounts/cc-user-panel.ui, panels/user-accounts/meson.build
Refresh implementation of https://github.com/endlessm/gnome-control-center/pull/206
https://phabricator.endlessm.com/T29440
___ 
Depends on meson build changes in #212 #211 (now merged)
=> Add launcher to launch parental controls app

panels/metrics/cc-metrics-panel.c, panels/metrics/cc-metrics-panel.ui
Also add a separate view for when metrics is disabled, similar to other panels.
Note that we don't have a metrics icon and neither a metrics-disabled icon so I went with "action-unavailable-symbolic" which looks quite Ok as a temp solution.
This PR includes the fixup from @uajain + a few other fixes, I pushed everything as a single fixup! commit on top of Umang changes as they are all fixups anyway, but let me know if you prefer to split the changes in separate commits.
https://phabricator.endlessm.com/T29571
=> Fix UI glitches

panels/user-accounts/cc-user-panel.c, panels/user-accounts/cc-user-panel.ui
EOS 3.7 and older supported setting parental controls on administrator
accounts, as that was how Hack was set up (the child user account was an
administrator). EOS 3.8 supports creating a separate administrator
account and leaving the child (main) user as a non-administrator.
Support for setting parental controls on an administrator account has
been dropped.
This commit adds a transitional message to direct users towards the
relevant FAQ entry about the change, which will give them information
about how to reconfigure their users so they can continue to apply
parental controls to their child.
This should not be upstreamed. It can be dropped from EOS 3.9 onwards.
https://phabricator.endlessm.com/T29385
=> eos: Add a transitional message about parental controls for admins

panels/user-accounts/cc-password-dialog.c
This avoids the situation where when changing the users's own password accounts service will request a polkit authorization for the action `org.freedesktop.accounts.change-own-password` (which is by default configured to not keep admin auth) twice, first to reset the password to an empty one which expects the current/old password and another auth request to change the password mode, with this request expecting an empty password (reset in previous request) but then gnome-shell won't allow the user to authenticate with an empty (opposed to None) password (which is strange anyway).
Note that this issue doesn't happen when the user we are trying to remove the password from has password mode set to set-at-login, given in this case it would mean we are not trying to remove our own password and …
=> user-accounts: Only reset password when removing password if previous mode was set-at-login

panels/display/cc-display-config-dbus.c, panels/display/cc-display-config.c, panels/display/cc-display-config.h, panels/display/cc-display-settings.c
This reverts commit 98c31b355ebd2f8d74a7dc9a3124d2c36f2af151.
This depends on a (breaking) change to the Mutter D-Bus API that we don't currently have in our Mutter. Back out this feature so that those of us dogfooding master can configure our monitors :)
https://phabricator.endlessm.com/T30174
=> Revert "display: Add a method to retrieve the name of a monitor mode"

panels/camera/cc-camera-panel.ui, panels/location/cc-location-panel.ui, panels/microphone/cc-microphone-panel.ui
These toggles only apply to the portal system, so only restrict access
for sandboxed apps. System apps (installed without sandboxing into
`/usr/bin`) can always access these resources on typical distributions.
In future, perhaps integration with a MAC (like SELinux) could restrict
access to the camera/microphone/GPS for system applications — but we
invented sandboxing to avoid having to do that, so it seems unlikely
that’s ever going to be implemented. If it is, this wording can change
again.
Upstream: https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/851
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
Fixes: #741
https://phabricator.endlessm.com/T27784
=> privacy: Mention that system apps can always use the camera/microphone

panels/updates/cc-updates-panel.c, panels/updates/meson.build
This will give us some measure of how many people are using automatic
updates, and how many of those are on metered connections.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
https://phabricator.endlessm.com/T29248
=> updates: Send a metric when automatic updates settings change

panels/updates/cc-updates-panel.c
Fix a crash when finalising the updates panel (for example, by switching
to another panel). This seems to have started being triggered by a
recent change in when NetworkManager emits the `NMClient:notify` signal.
The signal is now emitted during the update panel’s `finalize()`
function, causing it to try and update the UI with various freed or
`NULL` values.
This can be squashed into the original commit when we next rebase.
https://phabricator.endlessm.com/T31171
=> fixup! updates: Introduce Automatic Updates panel

panels/region/cc-input-chooser.c, panels/region/cc-input-chooser.ui, panels/region/cc-region-panel.ui
This reverts commit e5752b63e87b1b5269f00a8421ecd094be6bd63f.
The change was rejected upstream at
https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/823.
https://phabricator.endlessm.com/T11054
=> Revert "region: Change "Input Sources" label"

panels/applications/cc-applications-panel.c
We are removing all web links from the OS, let's remove the special handling here also.
Depends on whether we are also dropping image personalities' specific web links - see endlessm/eos-image-builder#975.
https://phabricator.endlessm.com/T31560
=> applications: Remove eos-link-* special handling

panels/info-overview/cc-info-overview-panel.c, panels/info-overview/cc-info-overview-panel.ui
By default info-overview panel shows the Gnome logo from a static
resource, currently every distro patches this component to show their logos
info-overview panel could use `/etc/os-release` file to fetch the OS logo
instead this static resource
(This is a clean zero-conflict backport from the GNOME 40 release)
https://phabricator.endlessm.com/T26931
=> info-overview: Implements usage of os-release to search for the OS logo

panels/metrics/cc-metrics-panel.c, panels/metrics/cc-metrics-panel.ui
Starting from Endless OS 4, no identifier is stored or
generated by the daemon.
This must be squashed with bcf9fd670438e5 during the
next rebase.
https://phabricator.endlessm.com/T32453
=> metrics: Remove metrics identifier

panels/applications/cc-applications-panel.c, panels/metrics/meson.build, panels/updates/meson.build
This reverts commit 13c14a3c7a5983f8deb2ee895fec22e337c33ca8.
As of T33045, the change in downstream gnome-software to make it hide
itself has been dropped. This means that the “Show in App Center” button
should now work for gnome-software in gnome-control-center.
This commit and the one it reverts can be dropped next time we rebase.
https://phabricator.endlessm.com/T33045
=> Revert "applications: hide “Show in App Center” for App Center"

shell/cc-window.c, shell/meson.build
This reverts commit d1a25f52ea7fdf1cf4ef41ee4f52b3669130182c.
This event has not been ingested on the server since the switch to the
new v3 protocol & data model in eos4.0.
https://phabricator.endlessm.com/T35145
=> Revert "eos: Add metric for opening a panel"

panels/user-accounts/cc-add-user-dialog.c, panels/user-accounts/cc-add-user-dialog.ui
In the previous version of this patch (6d3efcbb03b27b6e580f437e10ab2b0227e0dc96), there were two mistakes:
- `password_mode_changed_cb` was receiving arguments in the wrong order, such that `GtkCheckButton *button` was actually a `CcAddUserDialog`, and `CcAddUserDialog *self` was actually a `GtkCheckButton`. I solved it by adding `swapped="no"` to the signal handler in the UI file. (Despite conventional understanding of how opposites work, `swapped="yes"` is the default).
- `password_mode_changed_cb` was incorrectly treating the `local_password_radio` button like the `local_login_password_radio` button. We have some really similar code in our patch for `cc-password-dialog.c` (261a9b9689fda13ab605e3b38fbedd5edd4dc91d). I made sure these two match each other.
I was wondering how that …
=> fixup! user-accounts: Allow to create a user without a password

.gitmodules, debian/rules
gnome-control-center has code that looks up LOGO from /etc/os-release, and then sets the icon search list to [$LOGO-text, $LOGO] (or in dark mode [$LOGO-text-dark, $LOGO-text, $LOGO-dark, $LOGO]. On Endless OS we have LOGO=endlessos in os-release. The eos-logos package ships /usr/share/pixmaps/endlessos.svg and
/usr/share/pixmaps/endlessos-text.svg. So the text version is preferred.
However Debian's packaging sets the distributor_logo and dark_mode_distributor_logo build options to non-empty paths, specifically /usr/share/icons/vendor/scalable/emblems/emblem-vendor.svg. We do not install any file at that path, so Settings → About shows no logo.
Remove these build flags, restoring the logo displayed in EOS 5.
https://phabricator.endlessm.com/T35355
=> Don't specify [dark_mode_]distributor_logo
