endlessm/gnome-control-center

- panels/user-accounts/data/account-dialog.ui
- panels/user-accounts/data/password-dialog.ui
- panels/user-accounts/um-account-dialog.c
- panels/user-accounts/um-password-dialog.c
When setting the password, set also the password reminder.
[endlessm/eos-shell#1623]
> Add password reminder

- panels/background/cc-background-panel.c
> background: default backgrounds have moved

- panels/user-accounts/um-account-dialog.c
To be consistent with the rest of the file
> user-accounts: improve indentation/style

- panels/notifications/edit-dialog.ui
- panels/notifications/notifications.ui
- panels/privacy/privacy.ui
This PR removes the 'Notification on Lock Screen' property from the Privacy and Notifications panels.
https://phabricator.endlessm.com/T4802
> Remove the notification on lock screen property

- panels/bluetooth/cc-bluetooth-panel.c
https://bugzilla.gnome.org/show_bug.cgi?id=764696
https://phabricator.endlessm.com/T5599
> bluetooth: set switch off when BT airplane mode is enabled

- panels/background/cc-background-panel.c
This reverts commit da20f2f6a33e0f4cd4463e31bb66e549fb1b32c6.
Conflicts:
panels/background/cc-background-panel.c
https://phabricator.endlessm.com/T10782
> Revert "background: set default background from language"

- panels/info/cc-info-panel.c
- panels/info/info.ui
Per suggestions on the bug report, move the build
id into a separate row.
https://phabricator.endlessm.com/T4827
> info: move the build id into a separate row

- debian/rules
https://phabricator.endlessm.com/T15836
> Specify location for our vendor overrides

- panels/user-accounts/um-password-dialog.c
user panel, password: add fallback kbd layout if necessary
If the current keyboard layout is not a latin one we will add the fallback kbd layout 'en'. This calls out to gnome-shell where the logic to detect the keyboard layout is kept. The layout will be available in the popup switcher and the taskbar keyboard layout switcher.
https://phabricator.endlessm.com/T18598
> user panel, password: add fallback kbd layout if necessary

- panels/common/gsd-device-manager-x11.c
The dance we do to fetch event nodes from devices seems a bit superfluous
now, and even wrong if multiple X11 devices boil down to the same event
node.
Fixes the wacom panel not showing the "Map buttons..." action on older
kernels and wacom.ko modules, because the pad device shares the event node
with the stylus. Pad device lookups in order to enable the action obtain
the stylus device, thus the action is not shown.
https://bugzilla.gnome.org/show_bug.cgi?id=793029
> common: Use GdkDevices directly as HT keys on GsdDeviceManagerX11

- panels/updates/cc-tariff-editor.c
So that their tariff recurs on the same hour of the day, regardless of
whether they are in daylight savings.
https://phabricator.endlessm.com/T21500
> updates: Create recurring tariff periods in the user’s local timezone

- panels/updates/cc-updates-panel.c
The Automatic Updates panel should represent the current
state of the network. That means that, whenever an external
tool changes the automatic updates settings, the panel must
react to those changes and always display the most updated
value.
This is currently not the case, though, since it is not
reacting to the current connection changes, potentially
showing obsolete values.
Fix that by properly storing and connecting to the connection's
changed signal, and updating the settings when the signal is
fired.
https://phabricator.endlessm.com/T21823
> updates: React to network changes

- panels/display/cc-display-panel.c
https://phabricator.endlessm.com/T22815
> display: Hide unsupported resolutions again 

- configure.ac
- panels/user-accounts/Makefile.am
- panels/user-accounts/um-photo-dialog.c
Instead of a custom build option.
https://phabricator.endlessm.com/T23766
> user-accounts: use vendor file for alternative faces directory

- panels/info/cc-info-overview-panel.c
https://phabricator.endlessm.com/T23646
Related: https://github.com/endlessm/gnome-initial-setup/pull/271
> info: Support multi product EULA

- configure.ac
- panels/background/cc-background-xml.c
- panels/info/Makefile.am
- panels/user-accounts/Makefile.am
https://phabricator.endlessm.com/T24867
> background: Add support for vendor file wallpaper directory

- configure.ac
- panels/user-accounts/Makefile.am
- panels/user-accounts/data/app-permissions.ui
- panels/user-accounts/data/user-accounts-dialog.ui
- panels/user-accounts/gs-content-rating.c
- panels/user-accounts/gs-content-rating.h
- panels/user-accounts/um-app-permissions.c
- panels/user-accounts/um-app-permissions.h
- panels/user-accounts/um-user-panel.c
- panels/user-accounts/user-accounts.gresource.xml
- po/POTFILES.in
This is the initial version of the App Permissions section of the User Accounts panel. I'm pretty sure there are improvements to be made, but as of now, it already works.
> Add App Permissions to User Accounts panel

- panels/user-accounts/um-app-permissions.c
> T23897 Fix blacklisting flatpak apps installed system-wide

- panels/user-accounts/org.gnome.controlcenter.user-accounts.policy.in
- panels/user-accounts/um-app-permissions.c
- panels/user-accounts/um-app-permissions.h
- panels/user-accounts/um-user-panel.c
> T23897 Control sensitivity and visibility of parental controls widgets

- panels/user-accounts/um-app-permissions.c
> T23897 Minor fixes for rating system locale handling

- panels/user-accounts/data/app-permissions.ui
- panels/user-accounts/data/gnome-user-accounts-panel.desktop.in.in
- panels/user-accounts/data/user-accounts-dialog.ui
- panels/user-accounts/um-app-permissions.c
- panels/user-accounts/um-carousel.c
- panels/user-accounts/um-user-panel.c
Various minor usability improvements from https://phabricator.endlessm.com/T25063.
Includes various translatable string changes,.
> T25063 Parental controls usability improvements

- panels/user-accounts/data/app-permissions.ui
https://phabricator.endlessm.com/T25063
> user-accounts: Allow longer labels to wrap if translations are long

- panels/network/net-device-mobile.c
- panels/printers/pp-printer-entry.c
- panels/user-accounts/um-app-permissions.c
- po/POTFILES.in
This also includes two trivial patches cherry-picked from upstream to fix a couple of unrelated compiler warnings I saw while building this.
https://phabricator.endlessm.com/T25169
> T25169 Allow unsetting OARS filter

- panels/user-accounts/um-app-permissions.c
This is based on the branch for #157. Only the top commit is relevant.
https://phabricator.endlessm.com/T25171
> T25171 Reload parental controls apps list when apps are installed/uninstalled

- panels/user-accounts/um-app-permissions.c
App blacklisting is done on the basis of the flatpak ID of an app.
LibreOffice has a single flatpak ID shared between all its components,
but installs multiple .desktop files with different desktop file IDs, so
they get listed separately in the parental controls app list. However,
blacklisting one of them toggles the blacklist status for all other
LibreOffice components, which is not an expected user behaviour.
Fix this by hiding all apps which have the same flatpak ID as one
already listed. Select the one to show as the one with the shortest
desktop file ID, since this will typically be the ‘main’ .desktop file
whose ID is a prefix of all the others.
https://phabricator.endlessm.com/T25172
---
Only the top-most commit is relevant …
> T25172 user-accounts: Hide apps with duplicate flatpak IDs

- panels/user-accounts/cc-app-permissions.c
https://phabricator.endlessm.com/T26957
> Allow filtering apps with X-Parental-Controls desktop file entry

- panels/applications/cc-applications-panel.c
- panels/applications/meson.build
https://phabricator.endlessm.com/T27010
> applications: Enforce Parental Controls settings

- panels/user-accounts/cc-app-permissions.c
https://phabricator.endlessm.com/T26968
> parental-controls: Enable parental-controls for Administrators

- panels/user-accounts/cc-app-permissions.ui
Signed-off-by: Andre Moreira Magalhaes <andre@endlessm.com>
> parental controls: Remove colons from UI labels

- panels/user-accounts/cc-app-permissions.ui
https://phabricator.endlessm.com/T27064
> parental controls: Set max char limit to browser section help label

- panels/user-accounts/cc-app-permissions.c
https://phabricator.endlessm.com/T26995
> parental controls: Properly initialize selected age

- panels/applications/cc-applications-panel.c
- panels/applications/meson.build
- panels/search/cc-search-panel.c
- panels/search/meson.build
- panels/user-accounts/cc-app-permissions.c
- panels/user-accounts/cc-app-permissions.ui
- panels/user-accounts/gs-content-rating.c
- panels/user-accounts/gs-content-rating.h
- panels/user-accounts/meson.build
https://phabricator.endlessm.com/T27387
> Merge browser + administrator parental controls support to eos3.6

- panels/background/cc-background-preview.c
- panels/background/cc-background-preview.ui
- panels/background/preview.css
https://phabricator.endlessm.com/T27897
> Fix desktop and lock screen previews to look like EndlessOS

- po/fr.po
- po/hi.po
I have manually fixed the broken strings in the Transifex web UI. My French and Hindi are really improving!
I will merge this assuming the PR builds successfully.
https://phabricator.endlessm.com/T27764
> Updates from Transifex

- po/ar.po
- po/el.po
- po/en_CA.po
- po/en_GB.po
- po/hr.po
- po/is.po
- po/it.po
- po/nl.po
- po/pa.po
- po/pt_BR.po
- po/zh_TW.po
It really would have helped to pull *all* the languages.
https://phabricator.endlessm.com/T27764
> More updates from Transifex

- panels/user-accounts/cc-avatar-chooser.c
- shell/org.gnome.ControlCenter.gschema.xml
https://phabricator.endlessm.com/T28364
> Avatar faces in gsettings-desktop-schemas

- panels/user-accounts/cc-app-permissions.c
In the Users panel, a user can view their own parental controls
settings, such as what apps they can use, but non-admin users cannot
view other user's parental controls info, unless the panel is unlocked
by an admin using the "Unlock" button in the top right. This is because
in /usr/share/polkit-1/rules.d/com.endlessm.ParentalControls.rules we
only allow admins to view other user's parental controls. In case a
non-admin user is viewing another user's account, we currently try to
get the parental controls info with mct_manager_get_app_filter() even
though it won't be successful, because we can just not show that
information on failure. However due to a bug in accountsservice, an
unresponsive polkit dialog appears in this case despite libmalcontent
not using …
> T28600 unresponsive polkit dialog (temp fix)

- debian/rules
https://phabricator.endlessm.com/T29440
___
Associated code branch : https://github.com/endlessm/gnome-control-center/pull/211
> rules: Enable malcontent support

- panels/user-accounts/cc-avatar-chooser.c
https://phabricator.endlessm.com/T30095
> fixup! user-accounts: Use custom setting to override faces

- panels/metrics/cc-metrics-panel.ui
Update the ui file for the libhandy upgrade to 1.0 (currently we have
0.90 which is a preview of 1.0). See the documentation in
subprojects/libhandy/doc/hdy-migrating-0-0-to-1.xml
https://phabricator.endlessm.com/T30174
> fixup! privacy: Add metrics panel controlling metrics service integration

- panels/background/cc-background-preview.ui
- panels/user-accounts/cc-avatar-chooser.c
- panels/user-accounts/cc-crop-area.c
- panels/wacom/calibrator/calibrator-gui.c
https://phabricator.endlessm.com/T30174
> T30174 Minor rebase fixes

- shell/cc-window.c
- shell/meson.build
https://phabricator.endlessm.com/T18443
https://phabricator.endlessm.com/T27323
> eos: Add metric for opening a panel

- panels/updates/cc-tariff-editor.c
- panels/updates/cc-updates-panel.c
See the commit messages.
https://phabricator.endlessm.com/T31171
> T31171 Another fix for an updates panel crash

- panels/updates/cc-tariff-editor.c
https://phabricator.endlessm.com/T31171
> T31171 Tariff timezones

- panels/common/cc-common-language.c
gnome-initial-setup has been updated to use the upstream vendor config files at `/etc/gnome-initial-setup/vendor.conf` and `/usr/share/gnome-initial-setup/vendor.conf`. Our downstream `/var/lib/eos-image-defaults/branding/gnome-initial-setup.conf` config file is no longer being used. Adjust the language list population accordingly.
This can be squashed with 39117fc374 on the next rebase.
https://phabricator.endlessm.com/T35040
I think this could probably be sent upstream since it's now using g-i-s upstream paths.
> fixup! Populate language chooser with FBE vendor config file
